### ISSUE TITLE
Client gives Error: The project is finished! even though it is not.

### ISSUE THREAD

**Issue by marvk** [Hagmar/autoplace#4]
Coordinates 458 863

Image http://i.imgur.com/M68dyEu.png

Also might I suggest that the script keeps maintaining a finished project in case it gets griefed?

**Comment by Hagmar** [comment]
Hmm, I'm not able to reproduce this either...

**Comment by marvk** [comment]
Huh, weird. I can't figure out why this wouldn't work on my end 🤷

**Comment by Hagmar** [comment]
Are you sure that your colors are 100% correct in the image? If even a single channel is off by one then the script will assume that pixel is to be ignored. See the readme for the allowed colors
